<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Program with JavaScript Operators, Methods, and Keywords</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <style type="text/css">
        .spanSingleChoice {
            padding-left: 72px;
            width: 97%;
            min-height: 50px;
            overflow: inherit;
            padding-top: 10px !important;
            padding-bottom: 10px !important;
            white-space: pre-line;
        }

        .jsQuestion {
            padding: 5px;
            background-color: antiquewhite;
        }

        .jsAnswers {
            padding: 5px;
            background-color: aquamarine;
        }

        .jsExplanation {
            padding: 5px;
            background-color: khaki;
        }

        .jsConcepts {
            padding: 25px;
            font-size: large;
            background-color: aliceblue;
        }

        .jsSubConcepts {
            padding: 25px;
            font-size: medium;
            background-color: azure;
        }
    </style>
</head>
<body>
<div class="jsConcepts">
    Program with JavaScript Operators, Methods, and Keywords
</div>
<div class="jsSubConcepts">
    SubObjective:</p><p>Implement exception handling<br><br>
</div>
<div class="jsQuestion">
    <div id="questionStem" class="stem" style="height: 975px;"><p id="stemText" class="stemFont">The
        experimentWithTries() function in the following HTML page throws and catches exceptions:
        <code>
            <br><br>&lt;!DOCTYPE html&gt;
            <br>&lt;html&gt;
            <br>&lt;head&gt;
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;title&gt;Intro to JavaScript&lt;/title&gt;
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;meta charset="utf-8" /&gt;
            <br>&lt;/head&gt;
            <br>&lt;body&gt;
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;script&gt;
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; experimentWithTries();

            <br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; function experimentWithTries() {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            try {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log('Starting the process...');
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            throw new Error('Something went wrong');
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log('Ending the process...');
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            catch (ex) {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log(ex);
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            throw new Error(ex);
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            finally {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log('The inner finally block')
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch (ex) {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log(ex);
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; finally {
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log('The outer finally block')
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            console.log('Glad
            to be done!');
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;/script&gt;
            <br>&lt;/body&gt;
            <br>&lt;/html&gt;
        </code>
        <br><br>What will be displayed in the console when the page is loaded in the browser?</p></div>
</div>
<div class="jsAnswers">
    <div id="application" class="scrollable" style="width: 100%; max-width: 960px; height: 100%;">
        <div id="mainSlide" style="width: 100%; max-width: 960px; ">
            <div id="backgroundWidget" class="widgets" style="width:100%;height:100%">

            </div>
            <div tabindex="1" class="dd-handle-SR widgets null col-xs-12 correctAnswer"
                 style="left: 20px; margin-top: 2%; width: 920px; height: auto;"><input id="radio0" cid="c448"
                                                                                        class="widgets pointer radioButtonNone"
                                                                                        type="radio"
                                                                                        name="abMTA98382021"
                                                                                        value="$$abMTA_98-382-021_option0"
                                                                                        style="display:block;">
                <span id="span_radio0" style="position: relative !important;display: block;" class="spanSingleChoice">Starting the process...
Error: Something went wrong
The inner finally block  
Error: Error: Something went wrong
The outer finally block  
Glad to be done!</span></div>
            <div tabindex="1" class="dd-handle-SR widgets null col-xs-12"
                 style="left: 20px; width: 920px; height: auto; margin-top: 0px;"><input id="radio3" cid="c451"
                                                                                         class="widgets pointer radioButtonNone"
                                                                                         type="radio"
                                                                                         name="abMTA98382021"
                                                                                         value="$$abMTA_98-382-021_option3"
                                                                                         style="display:block;">
                <span id="span_radio3" style="position: relative !important;display: block;" class="spanSingleChoice">Starting the process...
Error: Something went wrong 
Error: Error: Something went wrong
The outer finally block  
Glad to be done!</span></div>
            <div tabindex="1" class="dd-handle-SR widgets null col-xs-12"
                 style="left: 20px; width: 920px; height: auto; margin-top: 0px;"><input id="radio1" cid="c449"
                                                                                         class="widgets pointer radioButtonNone"
                                                                                         type="radio"
                                                                                         name="abMTA98382021"
                                                                                         value="$$abMTA_98-382-021_option1"
                                                                                         style="display:block;">
                <span id="span_radio1" style="position: relative !important;display: block;" class="spanSingleChoice">Starting the process...
Error: Something went wrong
Ending the process...
The inner finally block  
Error: Error: Something went wrong
The outer finally block  
Glad to be done!</span></div>
            <div tabindex="1" class="dd-handle-SR widgets null col-xs-12"
                 style="left: 20px; width: 920px; height: auto; margin-top: 0px;"><input id="radio2" cid="c450"
                                                                                         class="widgets pointer radioButtonNone"
                                                                                         type="radio"
                                                                                         name="abMTA98382021"
                                                                                         value="$$abMTA_98-382-021_option2"
                                                                                         style="display:block;">
                <span id="span_radio2" style="position: relative !important;display: block;" class="spanSingleChoice">Starting the process...
Error: Something went wrong
The inner finally block  
The outer finally block  
Glad to be done!</span></div>
        </div>
    </div>

</div>
</div>
<button onclick=$('#showanswer').toggle()>Show/Hide Answer</button>
<div id="showanswer" class="jsExplanation" style="display: none">

    <div id="explanationDiv" style="">
        <div id="explanationHeader">
            <div id="expandExplanation" class="collapseExplanation"></div>
            <p id="explanationHeaderText">Explanation</p>
        </div>
        <div id="explanationBody" class="scrollable">
            <p id="explanationBodyText">The following will be displayed in the console:

                <br><br>Starting the process...
                <br>Error: Something went wrong
                <br>The inner finally block
                <br>Error: Error: Something went wrong
                <br>The outer finally block
                <br>Glad to be done!

                <br><br>When working with errors/exceptions, the code in question is placed inside a try block. If an
                error happens, control is transferred to the catch block(s) to handle the specific error. Then the
                finally block gets executed, whether or not there was an exception. These steps happen even if there are
                nested try/catch blocks.

                <br><br>In this example, the function starts with a nested try/catch block. The first log is written to
                the console (Starting the process...). Then an exception is thrown. The second log will not get executed
                because the control is transferred immediately to the catch block. The catch block logs the exception
                (Error: Something went wrong), and throws it again. However, before the transfer to the out try/catch
                happens, the finally block will run (The inner finally block). The outer catch block catches and logs
                the exception (Error: Error: Something went wrong), and the corresponding finally block is executed (The
                outer finally block). Then, the last log statement is written to the console (Glad to be done!).
                <br><br>
            <p>Objective:</p>
            <p>Program with JavaScript Operators, Methods, and Keywords</p>
            <p>SubObjective:</p>
            <p>Implement exception handling<br><br></p>
            <p>References</p>
            <p>MDN</p>
            <p>Mozilla</p>
            <p>try...catch</p>
            <p><a target="_blank"
                  href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch"
                  tabindex="190">Click here for more information</a></p><br>
            <p>MDN</p>
            <p>Mozilla</p>
            <p>throw</p>
            <p><a target="_blank"
                  href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw"
                  tabindex="190">Click here for more information</a></p><br></p>
        </div>
    </div>
</div>
<div id="console" class="hidden"></div>
</div>
<div id="hintDialog"></div>
</div>
</div>
</div>

</div>


</body>
</html>